export const verifiedProjects = [
  {
    id: "bennett-university-mobility-hub",
    name: "Bennett University Mobility Hub & Student Corridor",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "infrastructure",
    status: "ongoing",
    latitude: 28.450643,
    longitude: 77.5837983,
    geo_precision: "site_anchor",
    budget_inr_crore: 220,
    budget_display: "₹220 crore",
    timeline_display: "2025–2027",
    completion_percent: 35,
    impact_summary:
      "Upgrades pedestrian, shuttle, and safety infrastructure around the Bennett University campus.",
    description:
      "Adds a multimodal student mobility hub, safer crossings, and last‑mile access to TechZone II.",
    source_name: "Project Demo",
    source_date: "2025-06-01",
    source_url: "https://www.latlong.net/poi/bennett-university-682078",
    location_label: "Bennett University, TechZone II",
    geofence_radius_m: 3000,
  },
  {
    id: "bharat-mandapam-civic-hub",
    name: "Bharat Mandapam Civic Mobility Hub & Public Plaza",
    city: "New Delhi",
    state: "Delhi",
    type: "infrastructure",
    status: "ongoing",
    latitude: 28.61944,
    longitude: 77.2425,
    geo_precision: "site_anchor",
    budget_inr_crore: 780,
    budget_display: "₹780 crore",
    timeline_display: "2024–2027",
    completion_percent: 42,
    impact_summary:
      "Integrated public plaza, pedestrian spine, and multimodal drop-off upgrade supporting Bharat Mandapam footfall.",
    description:
      "Creates a shaded civic forecourt, improved pedestrian circulation, and upgraded transport access around the Bharat Mandapam convention campus.",
    source_name: "Project Demo",
    source_date: "2024-08-01",
    source_url: "https://en.wikipedia.org/wiki/Bharat_Mandapam",
    location_label: "Bharat Mandapam, Pragati Maidan",
    geofence_radius_m: 3000,
  },
  {
    id: "mumbai-metro-line-2a",
    name: "Mumbai Metro Line 2A (Dahisar East-DN Nagar)",
    city: "Mumbai",
    state: "Maharashtra",
    type: "metro",
    status: "completed",
    latitude: 19.1875,
    longitude: 72.8535,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2023-01-19",
    completion_percent: 100,
    impact_summary: "Adds east-west metro capacity for Mumbai and supports cleaner urban mobility.",
    description:
      "Dedicated to the nation as part of Mumbai's metro expansion. The source groups Line 2A with Line 7 at about Rs 12,600 crore without a split by corridor.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "Representative midpoint between Dahisar East and DN Nagar",
    geofence_radius_m: 2500,
  },
  {
    id: "mumbai-metro-line-7",
    name: "Mumbai Metro Line 7 (Andheri East-Dahisar East)",
    city: "Mumbai",
    state: "Maharashtra",
    type: "metro",
    status: "completed",
    latitude: 19.196,
    longitude: 72.872,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2023-01-19",
    completion_percent: 100,
    impact_summary: "Improves north-south suburban travel and helps decongest road corridors in Mumbai.",
    description:
      "Dedicated with Line 2A in the same official release. Budget is only provided as a combined figure for both metro lines.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "Representative midpoint between Andheri East and Dahisar East",
    geofence_radius_m: 2500,
  },
  {
    id: "malad-stp",
    name: "Malad Sewage Treatment Plant",
    city: "Mumbai",
    state: "Maharashtra",
    type: "wastewater",
    status: "planned",
    latitude: 19.187,
    longitude: 72.798,
    geo_precision: "locality_anchor",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2023-01-19",
    completion_percent: null,
    impact_summary: "Part of Mumbai's 2,460 MLD sewage-treatment capacity expansion.",
    description:
      "One of seven sewage treatment plants announced together in Mumbai. The official release gives only the combined cost for all seven plants.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "Malad",
    geofence_radius_m: 1800,
  },
  {
    id: "bhandup-stp",
    name: "Bhandup Sewage Treatment Plant",
    city: "Mumbai",
    state: "Maharashtra",
    type: "wastewater",
    status: "planned",
    latitude: 19.145,
    longitude: 72.937,
    geo_precision: "locality_anchor",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2023-01-19",
    completion_percent: null,
    impact_summary: "Part of Mumbai's 2,460 MLD sewage-treatment capacity expansion.",
    description:
      "One of seven sewage treatment plants announced together in Mumbai. The official release gives only the combined cost for all seven plants.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "Bhandup",
    geofence_radius_m: 1800,
  },
  {
    id: "bhandup-multispeciality-hospital",
    name: "Bhandup Multispeciality Municipal Hospital Redevelopment",
    city: "Mumbai",
    state: "Maharashtra",
    type: "hospital",
    status: "planned",
    latitude: 19.145,
    longitude: 72.935,
    geo_precision: "locality_anchor",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2023-01-19",
    completion_percent: null,
    impact_summary: "Adds a 360-bed municipal hospital to strengthen healthcare access for local residents.",
    description:
      "The release states this redevelopment is expected to benefit lakhs of residents and deliver top-class medical facilities.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "Bhandup",
    geofence_radius_m: 1500,
  },
  {
    id: "csmt-redevelopment",
    name: "Chhatrapati Shivaji Maharaj Terminus Redevelopment",
    city: "Mumbai",
    state: "Maharashtra",
    type: "railway-station",
    status: "planned",
    latitude: 18.9401,
    longitude: 72.8354,
    geo_precision: "station_anchor",
    budget_inr_crore: 1800,
    budget_display: "₹1,800 crore",
    timeline_display: "Foundation stone laid on 2023-01-19",
    completion_percent: null,
    impact_summary: "Aims to decongest the heritage terminus and improve multimodal integration.",
    description:
      "The redevelopment is designed to improve passenger facilities while restoring the iconic station and integrating it better with other transport modes.",
    source_name: "PIB",
    source_date: "2023-01-19",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1892302",
    location_label: "CSMT",
    geofence_radius_m: 1200,
  },
  {
    id: "visakhapatnam-railway-station-redevelopment",
    name: "Visakhapatnam Railway Station Redevelopment",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "railway-station",
    status: "planned",
    latitude: 17.7215,
    longitude: 83.3095,
    geo_precision: "station_anchor",
    budget_inr_crore: 450,
    budget_display: "₹450 crore",
    timeline_display: "Foundation stone laid on 2022-11-12",
    completion_percent: null,
    impact_summary: "Expected to improve multimodal mobility and station capacity in a fast-growing coastal city.",
    description:
      "The redevelopment was announced with a stated three-year execution window in contemporary coverage of the launch event.",
    source_name: "India Infra Hub",
    source_date: "2022-10-29",
    source_url: "https://indiainfrahub.com/news/andhra-pradesh-prime-minister-modi-to-launch-development-projects-in-visakhapatnam-on-11-november/",
    location_label: "Visakhapatnam Junction",
    geofence_radius_m: 1800,
  },
  {
    id: "visakhapatnam-fishing-harbour-modernisation",
    name: "Visakhapatnam Fishing Harbour Modernisation and Upgradation",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "port",
    status: "planned",
    latitude: 17.6806,
    longitude: 83.2987,
    geo_precision: "harbour_anchor",
    budget_inr_crore: 150,
    budget_display: "₹150 crore",
    timeline_display: "Foundation stone laid on 2022-11-12",
    completion_percent: null,
    impact_summary: "Targets safer and more modern harbour infrastructure for the fisheries economy.",
    description:
      "Included in the Visakhapatnam development package announced during the Prime Minister's visit.",
    source_name: "PTI / Nagaland Tribune",
    source_date: "2022-11-12",
    source_url: "https://nagalandtribune.in/pm-launches-infra-projects-worth-rs-15233-cr-in-ap-lays-foundation-stone-for-redevelopment-of-vizag-railway-station/",
    location_label: "Visakhapatnam Fishing Harbour",
    geofence_radius_m: 1500,
  },
  {
    id: "raipur-visakhapatnam-economic-corridor-ap-section",
    name: "Raipur-Visakhapatnam Economic Corridor (Andhra Pradesh Section)",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "highway",
    status: "planned",
    latitude: 17.89,
    longitude: 83.34,
    geo_precision: "representative_corridor_anchor",
    budget_inr_crore: 3750,
    budget_display: "₹3,750 crore",
    timeline_display: "Foundation stone laid on 2022-11-12",
    completion_percent: null,
    impact_summary: "Strengthens freight connectivity between hinterland production zones and the coast.",
    description:
      "The project was announced as part of the Visakhapatnam package and serves as a key freight corridor link in Andhra Pradesh.",
    source_name: "PTI / Nagaland Tribune",
    source_date: "2022-11-12",
    source_url: "https://nagalandtribune.in/pm-launches-infra-projects-worth-rs-15233-cr-in-ap-lays-foundation-stone-for-redevelopment-of-vizag-railway-station/",
    location_label: "Representative Andhra Pradesh anchor on the corridor near Visakhapatnam district",
    geofence_radius_m: 3000,
  },
  {
    id: "convent-junction-sheela-nagar-port-road",
    name: "Convent Junction-Sheela Nagar Junction Port Road",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "road",
    status: "completed",
    latitude: 17.715,
    longitude: 83.245,
    geo_precision: "representative_corridor_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Dedicated on 2022-11-12",
    completion_percent: 100,
    impact_summary: "Improves port-side road connectivity for logistics movement in Visakhapatnam.",
    description:
      "Included among the projects dedicated during the Visakhapatnam event; the project supports port access and urban freight movement.",
    source_name: "PTI / Nagaland Tribune",
    source_date: "2022-11-12",
    source_url: "https://nagalandtribune.in/pm-launches-infra-projects-worth-rs-15233-cr-in-ap-lays-foundation-stone-for-redevelopment-of-vizag-railway-station/",
    location_label: "Representative midpoint between Convent Junction and Sheela Nagar Junction",
    geofence_radius_m: 2000,
  },
  {
    id: "narasannapeta-pathapatnam-nh326a",
    name: "Narasannapeta-Pathapatnam NH-326A Section",
    city: "Srikakulam",
    state: "Andhra Pradesh",
    type: "highway",
    status: "completed",
    latitude: 18.585,
    longitude: 84.064,
    geo_precision: "representative_corridor_midpoint",
    budget_inr_crore: 211,
    budget_display: "₹211 crore",
    timeline_display: "Dedicated on 2022-11-12",
    completion_percent: 100,
    impact_summary: "Improves road connectivity on the Srikakulam-Gajapati corridor.",
    description:
      "The release identifies the 39 km stretch as part of the Srikakulam-Gajapati corridor.",
    source_name: "PTI / Nagaland Tribune",
    source_date: "2022-11-12",
    source_url: "https://nagalandtribune.in/pm-launches-infra-projects-worth-rs-15233-cr-in-ap-lays-foundation-stone-for-redevelopment-of-vizag-railway-station/",
    location_label: "Representative midpoint between Narasannapeta and Pathapatnam",
    geofence_radius_m: 2200,
  },
  {
    id: "howrah-maidan-esplanade-metro",
    name: "Howrah Maidan-Esplanade Metro Section",
    city: "Kolkata",
    state: "West Bengal",
    type: "metro",
    status: "completed",
    latitude: 22.576,
    longitude: 88.342,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Introduces India's first underwater metro tunnel and helps decongest Kolkata-Howrah traffic.",
    description:
      "This section includes the Hooghly river crossing and Howrah Metro Station, described as the deepest metro station in India.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Howrah Maidan and Esplanade",
    geofence_radius_m: 2200,
  },
  {
    id: "kavi-subhash-hemanta-mukhopadhyay-metro",
    name: "Kavi Subhash-Hemanta Mukhopadhyay Metro Section",
    city: "Kolkata",
    state: "West Bengal",
    type: "metro",
    status: "completed",
    latitude: 22.503,
    longitude: 88.4,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Extends metro reach in south-eastern Kolkata and supports easier urban commuting.",
    description:
      "Flagged off along with several other metro and rapid-transit sections in the 2024 connectivity package.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Kavi Subhash and Hemanta Mukhopadhyay",
    geofence_radius_m: 1800,
  },
  {
    id: "taratala-majerhat-metro",
    name: "Taratala-Majerhat Metro Section",
    city: "Kolkata",
    state: "West Bengal",
    type: "metro",
    status: "completed",
    latitude: 22.516,
    longitude: 88.311,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Adds a new Joka-Esplanade segment and improves transfer options around Majerhat.",
    description:
      "The official release notes Majerhat as a unique elevated station spanning railway lines, platforms and a canal.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Taratala and Majerhat",
    geofence_radius_m: 1600,
  },
  {
    id: "pune-metro-ruby-hall-ramwadi",
    name: "Pune Metro Ruby Hall Clinic-Ramwadi Stretch",
    city: "Pune",
    state: "Maharashtra",
    type: "metro",
    status: "completed",
    latitude: 18.549,
    longitude: 73.912,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Expands urban rail access in Pune and helps shift trips away from road congestion.",
    description:
      "This stretch was inaugurated as part of the multi-city connectivity launch in March 2024.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Ruby Hall Clinic and Ramwadi",
    geofence_radius_m: 2000,
  },
  {
    id: "kochi-metro-phase-1b-tripunithura",
    name: "Kochi Metro Phase IB SN Junction-Tripunithura Stretch",
    city: "Kochi",
    state: "Kerala",
    type: "metro",
    status: "completed",
    latitude: 9.945,
    longitude: 76.36,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Extends Kochi Metro eastward and improves access to Tripunithura.",
    description:
      "The Phase IB extension was flagged off alongside other metro and rapid transit projects across India.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between SN Junction and Tripunithura",
    geofence_radius_m: 1700,
  },
  {
    id: "agra-metro-taj-east-gate-mankameshwar",
    name: "Agra Metro Taj East Gate-Mankameshwar Stretch",
    city: "Agra",
    state: "Uttar Pradesh",
    type: "metro",
    status: "completed",
    latitude: 27.173,
    longitude: 78.021,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Improves access to major historical sites and local urban destinations in Agra.",
    description:
      "The official release explicitly notes that this section will enhance connectivity to historical tourist places.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Taj East Gate and Mankameshwar",
    geofence_radius_m: 2200,
  },
  {
    id: "duhai-modinagar-north-rrts",
    name: "Delhi-Meerut RRTS Duhai-Modinagar North Section",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    type: "regional-rail",
    status: "completed",
    latitude: 28.981,
    longitude: 77.712,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Opened on 2024-03-06",
    completion_percent: 100,
    impact_summary: "Supports faster NCR regional travel and is expected to boost economic activity.",
    description:
      "Opened as part of the Delhi-Meerut RRTS corridor package highlighted in the 2024 connectivity release.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Duhai and Modinagar North",
    geofence_radius_m: 2400,
  },
  {
    id: "pune-metro-pimpri-nigdi-extension",
    name: "Pune Metro Phase 1 Pimpri Chinchwad-Nigdi Extension",
    city: "Pimpri-Chinchwad",
    state: "Maharashtra",
    type: "metro",
    status: "planned",
    latitude: 18.648,
    longitude: 73.758,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2024-03-06",
    completion_percent: null,
    impact_summary: "Will extend mass-transit coverage deeper into Pimpri-Chinchwad and Nigdi.",
    description:
      "The foundation stone for the extension was laid in the same official release that inaugurated the Ruby Hall Clinic-Ramwadi stretch.",
    source_name: "PIB",
    source_date: "2024-03-06",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2011855",
    location_label: "Representative midpoint between Pimpri Chinchwad and Nigdi",
    geofence_radius_m: 2200,
  },
  {
    id: "gurugram-metro-rail-project",
    name: "Gurugram Metro Rail Project",
    city: "Gurugram",
    state: "Haryana",
    type: "metro",
    status: "planned",
    latitude: 28.475,
    longitude: 77.083,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: 5450,
    budget_display: "₹5,450 crore",
    timeline_display: "Foundation stone laid on 2024-02-16",
    completion_percent: null,
    impact_summary: "Connects Millennium City Centre with Udyog Vihar Phase 5 and links into existing Gurugram metro systems.",
    description:
      "The project includes a Dwarka Expressway spur and is positioned as a major environment-friendly urban transport investment.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Representative midpoint between Millennium City Centre and Udyog Vihar Phase 5",
    geofence_radius_m: 2600,
  },
  {
    id: "aiims-rewari",
    name: "AIIMS Rewari",
    city: "Rewari",
    state: "Haryana",
    type: "hospital",
    status: "planned",
    latitude: 28.141,
    longitude: 76.621,
    geo_precision: "site_anchor",
    budget_inr_crore: 1650,
    budget_display: "₹1,650 crore",
    timeline_display: "Foundation stone laid on 2024-02-16",
    completion_percent: null,
    impact_summary: "Will provide tertiary care services and expand medical education capacity in Haryana.",
    description:
      "The institute is planned on 203 acres in village Majra Mustil Bhalkhi and includes a 720-bed hospital complex.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Majra Mustil Bhalkhi, Rewari",
    geofence_radius_m: 2200,
  },
  {
    id: "rewari-kathuwas-rail-doubling",
    name: "Rewari-Kathuwas Rail Line Doubling",
    city: "Rewari",
    state: "Haryana",
    type: "railway",
    status: "planned",
    latitude: 28.172,
    longitude: 76.64,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2024-02-16",
    completion_percent: null,
    impact_summary: "Augments rail capacity for both passenger and freight movement in south Haryana.",
    description:
      "The official release says the line doubling will help timely running of passenger and freight trains.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Representative midpoint between Rewari and Kathuwas",
    geofence_radius_m: 2200,
  },
  {
    id: "kathuwas-narnaul-rail-doubling",
    name: "Kathuwas-Narnaul Rail Line Doubling",
    city: "Narnaul",
    state: "Haryana",
    type: "railway",
    status: "planned",
    latitude: 28.041,
    longitude: 76.198,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2024-02-16",
    completion_percent: null,
    impact_summary: "Improves rail throughput and reliability on the Narnaul approach.",
    description:
      "Included in the Rewari railway package intended to strengthen both passenger and freight operations.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Representative midpoint between Kathuwas and Narnaul",
    geofence_radius_m: 2200,
  },
  {
    id: "bhiwani-dobh-bhali-rail-doubling",
    name: "Bhiwani-Dobh Bhali Rail Line Doubling",
    city: "Bhiwani",
    state: "Haryana",
    type: "railway",
    status: "planned",
    latitude: 28.64,
    longitude: 76.037,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2024-02-16",
    completion_percent: null,
    impact_summary: "Improves freight and passenger reliability on a key Haryana rail segment.",
    description:
      "One of the line-doubling projects announced during the Rewari development package.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Representative midpoint between Bhiwani and Dobh Bhali",
    geofence_radius_m: 2200,
  },
  {
    id: "rohtak-meham-hansi-rail-line",
    name: "Rohtak-Meham-Hansi Rail Line",
    city: "Rohtak",
    state: "Haryana",
    type: "railway",
    status: "completed",
    latitude: 29.11,
    longitude: 76.2,
    geo_precision: "representative_line_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Dedicated on 2024-02-16",
    completion_percent: 100,
    impact_summary: "Reduces travel time between Rohtak and Hisar and improves regional rail connectivity.",
    description:
      "The line was dedicated to the nation and train service was flagged off on the section.",
    source_name: "PIB",
    source_date: "2024-02-16",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2006554",
    location_label: "Representative midpoint on the Rohtak-Meham-Hansi section",
    geofence_radius_m: 2600,
  },
  {
    id: "aiims-jodhpur-trauma-centre",
    name: "AIIMS Jodhpur Trauma Centre and Critical Care Hospital Block",
    city: "Jodhpur",
    state: "Rajasthan",
    type: "hospital",
    status: "planned",
    latitude: 26.239,
    longitude: 73.035,
    geo_precision: "campus_anchor",
    budget_inr_crore: 350,
    budget_display: "₹350 crore",
    timeline_display: "Foundation stone laid on 2023-10-05",
    completion_percent: null,
    impact_summary: "Adds integrated trauma, emergency and critical-care capacity at AIIMS Jodhpur.",
    description:
      "The project includes diagnostics, wards, modular operating theatres, ICUs and dialysis areas.",
    source_name: "PIB",
    source_date: "2023-10-05",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1964539",
    location_label: "AIIMS Jodhpur",
    geofence_radius_m: 1500,
  },
  {
    id: "jodhpur-airport-terminal",
    name: "Jodhpur Airport New Terminal Building",
    city: "Jodhpur",
    state: "Rajasthan",
    type: "airport",
    status: "planned",
    latitude: 26.251,
    longitude: 73.049,
    geo_precision: "airport_anchor",
    budget_inr_crore: 480,
    budget_display: "₹480 crore",
    timeline_display: "Foundation stone laid on 2023-10-05",
    completion_percent: null,
    impact_summary: "Expands peak-hour handling capacity and supports tourism and regional connectivity.",
    description:
      "The terminal is designed for about 2,500 peak-hour passengers and 35 lakh annual passengers.",
    source_name: "PIB",
    source_date: "2023-10-05",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1964539",
    location_label: "Jodhpur Airport",
    geofence_radius_m: 1800,
  },
  {
    id: "jodhpur-ring-road-karwar-dangiyawas",
    name: "Karwar-Dangiyawas Section of Jodhpur Ring Road (NH-125A)",
    city: "Jodhpur",
    state: "Rajasthan",
    type: "road",
    status: "planned",
    latitude: 26.343,
    longitude: 73.03,
    geo_precision: "representative_corridor_anchor",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2023-10-05",
    completion_percent: null,
    impact_summary: "Expected to ease city traffic pressure and reduce vehicular pollution in Jodhpur.",
    description:
      "The project is part of a road package announced with a cumulative cost for multiple Rajasthan road works.",
    source_name: "PIB",
    source_date: "2023-10-05",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1964539",
    location_label: "Representative anchor on the Jodhpur Ring Road section",
    geofence_radius_m: 2600,
  },
  {
    id: "pachpadra-bagundi-nh25",
    name: "Pachpadra-Bagundi Section of NH-25",
    city: "Balotra",
    state: "Rajasthan",
    type: "highway",
    status: "planned",
    latitude: 25.94,
    longitude: 72.253,
    geo_precision: "representative_corridor_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Foundation stone laid on 2023-10-05",
    completion_percent: null,
    impact_summary: "Improves regional connectivity and supports trade and employment in western Rajasthan.",
    description:
      "This corridor work is part of the same multi-road Rajasthan package announced in Jodhpur.",
    source_name: "PIB",
    source_date: "2023-10-05",
    source_url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1964539",
    location_label: "Representative midpoint between Pachpadra and Bagundi",
    geofence_radius_m: 2600,
  },
  {
    id: "iim-shillong-umsawli-campus",
    name: "IIM Shillong New Campus at Umsawli",
    city: "Shillong",
    state: "Meghalaya",
    type: "education",
    status: "completed",
    latitude: 25.626,
    longitude: 91.825,
    geo_precision: "campus_anchor",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Inaugurated on 2022-12-18",
    completion_percent: 100,
    impact_summary: "Expands higher-education and professional opportunities in Meghalaya.",
    description:
      "The official release links the new campus to education and employment opportunities in the region.",
    source_name: "PIB",
    source_date: "2022-12-18",
    source_url: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1884553",
    location_label: "Umsawli",
    geofence_radius_m: 1600,
  },
  {
    id: "shillong-diengpasoh-road",
    name: "Shillong-Diengpasoh Road",
    city: "Shillong",
    state: "Meghalaya",
    type: "road",
    status: "completed",
    latitude: 25.606,
    longitude: 91.882,
    geo_precision: "representative_corridor_midpoint",
    budget_inr_crore: null,
    budget_display: "unknown",
    timeline_display: "Inaugurated on 2022-12-18",
    completion_percent: 100,
    impact_summary: "Provides better access to the new Shillong satellite township and helps decongest Shillong.",
    description:
      "The source explicitly calls out the road's role in satellite-township connectivity and congestion relief.",
    source_name: "PIB",
    source_date: "2022-12-18",
    source_url: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1884553",
    location_label: "Representative midpoint between Shillong and Diengpasoh",
    geofence_radius_m: 2200,
  },
];

export const verifiedProjectSourceSummary = {
  totalProjects: verifiedProjects.length,
  primarySources: [
    "PIB official releases",
    "PM India official release mirror for Meghalaya coverage",
    "Verified news coverage for Visakhapatnam package where the official release was less discoverable",
  ],
  geoNote:
    "Coordinates are representative anchors for named stations, campuses, facilities, or corridor midpoints. They are not cadastral survey points.",
};

function normalizeProject(project) {
  return {
    id: project.id,
    name: project.name,
    city: project.city,
    state: project.state,
    type: project.type,
    status: project.status,
    latitude: project.latitude,
    longitude: project.longitude,
    geoPrecision: project.geoPrecision ?? project.geo_precision ?? "point",
    budgetInrCrore: project.budgetInrCrore ?? project.budget_inr_crore ?? null,
    budgetDisplay: project.budgetDisplay ?? project.budget_display ?? "unknown",
    timelineDisplay: project.timelineDisplay ?? project.timeline_display ?? "unknown",
    completionPercent: project.completionPercent ?? project.completion_percent ?? null,
    impactSummary: project.impactSummary ?? project.impact_summary ?? "unknown",
    description: project.description ?? "",
    sourceName: project.sourceName ?? project.source_name ?? "unknown",
    sourceDate: project.sourceDate ?? project.source_date ?? null,
    sourceUrl: project.sourceUrl ?? project.source_url,
    locationLabel: project.locationLabel ?? project.location_label ?? `${project.city}, ${project.state}`,
    geofenceRadiusM: project.geofenceRadiusM ?? project.geofence_radius_m ?? 1500,
  };
}

export const normalizedVerifiedProjects = verifiedProjects.map(normalizeProject);
